version: '3.7'
services:
    mysqldb:
        container_name: sqldb
        image: mysql
        env_file: .env
        environment: 
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: football_results
        ports:
            - '3306:3306'
        networks:
            - webnet
        volumes:
            - mysql:/var/lib/mysql/data
            - mysql_config:/etc/mysql
    web:
        build:
            context: .
        env_file: ./.env
        command: npm start
        volumes: 
            - .:/app/
            - /app/node_modules
        ports:
            - '3000:3000'
            # - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        depends_on: 
            - mysqldb
        environment: 
            MYSQL_HOST: mysqldb
        networks:
            - webnet
networks:
  webnet:
volumes:
    mysql:
    mysql_config: